version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: sampledb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"

  tomcat:
    build: ./tomcat
    ports:
      - "8080:8080"
    depends_on:
      - postgres
