apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-replica-springboot
spec:
  serviceName: postgres-replica-springboot
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      role: replica
  template:
    metadata:
      labels:
        app: postgres
        role: replica
    spec:
      containers:
      - name: postgres
        image: postgres:15
        envFrom:
        - secretRef:
            name: postgres-secret
        command:
          - bash
          - "-c"
          - |
            if [ ! -s /var/lib/postgresql/data/PG_VERSION ]; then
              echo "Initializing replica from primary..."
              if ! pg_basebackup -h postgres-primary -U replicator -p 5432 -D /var/lib/postgresql/data/ -Fp -Xs -P -R; then
                echo "pg_basebackup failed with exit code $?."
                exit 1
              else
                echo "pg_basebackup completed successfully."
              fi
            fi
            echo "Starting PostgreSQL..."
            exec docker-entrypoint.sh postgres
        env:
        - name: REPLICA_ROLE
          value: "true"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-replica-data
          mountPath: /var/lib/postgresql/data
        - name: postgres-config
          mountPath: /etc/postgresql/postgresql.conf
          subPath: replica.conf
      volumes:
      - name: postgres-config
        configMap:
          name: postgres-config
  volumeClaimTemplates:
  - metadata:
      name: postgres-replica-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: springboot-demo
      resources:
        requests:
          storage: 10Gi
