apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-primary-springboot
spec:
  serviceName: postgres-primary-springboot
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      role: primary
  template:
    metadata:
      labels:
        app: postgres
        role: primary
    spec:
      containers:
      - name: postgres
        image: postgres:15
        envFrom:
        - secretRef:
            name: postgres-secret
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-primary-data
          mountPath: /var/lib/postgresql/data
        - name: postgres-config
          mountPath: /etc/postgresql/postgresql.conf
          subPath: primary.conf
      volumes:
      - name: postgres-config
        configMap:
          name: postgres-config
  volumeClaimTemplates:
  - metadata:
      name: postgres-primary-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: springboot-demo
      resources:
        requests:
          storage: 10Gi
