apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  namespace: springboot-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat-service
        image: tomcat:10.1-jdk21
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: tomcat-data
          mountPath: /usr/local/tomcat/
        # Resource limits and requests
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        # Environment variables
        env:
        - name: POSTGRES_HOST
          value: postgres-primary
        envFrom:
        - secretRef:
            name: postgres-secret
      volumes:
      - name: tomcat-data
        persistentVolumeClaim:
          claimName: tomcat-pvc
