# Use Ubuntu 24.04 as the base image
FROM ubuntu:24.04

# Install dependencies
RUN apt update && apt install -y \
    wget \
    gnupg2 \
    software-properties-common

RUN apt update && apt install -y \
    openjdk-21-jdk \
    maven \
    tomcat10

# Set environment variables
ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
ENV PATH=$PATH:$JAVA_HOME/bin

# Expose ports
# Tomcat
EXPOSE 8080

