apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  type: NodePort      # Added NodePort type
  selector:
    app: tomcat
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432

