apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=    # base64 encoded 'your_user'
  POSTGRES_PASSWORD: YWRtaW4xMjM=    # base64 encoded 'your_password'
  POSTGRES_DB: c2FtcGxlZGI=    # base64 encoded 'your_database'

