# tomcat/Dockerfile
FROM tomcat:9-jdk11

#COPY ROOT.war /usr/local/tomcat/webapps/
RUN cp -r /usr/local/tomcat/webapps.dist/* /usr/local/tomcat/webapps/

# Create a test index.html in ROOT
RUN echo '<html><body><h1>Welcome to Tomcat</h1></body></html>' > /usr/local/tomcat/webapps/ROOT/index.html

EXPOSE 8080