version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - webapp
    restart: unless-stopped

  webapp:
    build: ./tomcat
    expose:
      - "8080"
    environment:
      - CATALINA_OPTS=-Xmx512m
      - POSTGRES_HOST=db
      - POSTGRES_DB= sampledb
      - POSTGRES_USER= admin
      - POSTGRES_PASSWORD= admin123
    depends_on:
      - db
    restart: unless-stopped

  db:
    build: ./postgres
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB= sampledb
      - POSTGRES_USER= admin
      - POSTGRES_PASSWORD= admin123
    restart: unless-stopped

volumes:
  postgres_data: