apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: springboot-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-sa
      securityContext:
        fsGroup: 1000
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: jenkins
        image: agrawalram/k8s-springboot-demo:my-springboot-jenkins
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        resources:
          requests:
            cpu: "200m"  # Reduced CPU request
            memory: "1Gi"
          limits:
            cpu: "500m"  # Optionally reduced CPU limit
            memory: "2Gi"
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pvc
