apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-springboot-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: springboot-demo
  hostPath:
    path: /mnt/data/jenkins-0-springboot
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - svm-cmtit-vm5

