apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  primary.conf: |
    listen_addresses = '*'
    archive_mode = 'ON'
    wal_keep_segments = '10'
    max_connections = 100
    wal_level = 'replica'
    max_wal_senders = 10
    max_replication_slots = 10
    hot_standby = on
  replica.conf: |
    primary_conninfo = 'host=postgres-primary port=5432 user=replicator password=replicator application_name=postgres_replica'
    hot_standby = on
