apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  type: ClusterIP     # Added NodePort type
  selector:
    app: tomcat
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
